version: "3.0"
services:
  postgresql:
    image: postgres
    container_name: "postgres"
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db: